### ISSUE TITLE
springboot 2.5.2  引入 ydoc 1.1.2  报空指针

### ISSUE THREAD

**Issue by zhoukc** [NoBugBoy/YDoc#15]
![image](https://user-images.githubusercontent.com/18244668/145211889-06b8987d-db8f-4804-990e-951ab83f1860.png)

"C:\Program Files (x86)\Java\jdk-9\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:59760,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:C:\Users\w\.IntelliJIdea2019.2\system\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "D:\IdeaProjects\spider-man\target\classes;D:\Maven_Repository\org\jsoup\jsoup\1.13.1\jsoup-1.13.1.jar;D:\Maven_Repository\cn\wanghaomiao\JsoupXpath\2.4.3\JsoupXpath-2.4.3.jar;D:\Maven_Repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;D:\Maven_Repository\org\antlr\antlr4-runtime\4.7.2\antlr4-runtime-4.7.2.jar;D:\Maven_Repository\org\slf4j\slf4j-api\1.7.31\slf4j-api-1.7.31.jar;D:\Maven_Repository\cn\afterturn\easypoi-base\4.2.0\easypoi-base-4.2.0.jar;D:\Maven_Repository\org\apache\poi\poi\4.1.1\poi-4.1.1.jar;D:\Maven_Repository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;D:\Maven_Repository\org\apache\commons\commons-collections4\4.4\commons-collections4-4.4.jar;D:\Maven_Repository\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar;D:\Maven_Repository\org\apache\poi\poi-ooxml\4.1.1\poi-ooxml-4.1.1.jar;D:\Maven_Repository\org\apache\commons\commons-compress\1.19\commons-compress-1.19.jar;D:\Maven_Repository\com\github\virtuald\curvesapi\1.06\curvesapi-1.06.jar;D:\Maven_Repository\org\apache\poi\poi-ooxml-schemas\4.1.1\poi-ooxml-schemas-4.1.1.jar;D:\Maven_Repository\org\apache\xmlbeans\xmlbeans\3.1.0\xmlbeans-3.1.0.jar;D:\Maven_Repository\ognl\ognl\3.2.6\ognl-3.2.6.jar;D:\Maven_Repository\org\javassist\javassist\3.20.0-GA\javassist-3.20.0-GA.jar;D:\Maven_Repository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;D:\Maven_Repository\cn\afterturn\easypoi-annotation\4.2.0\easypoi-annotation-4.2.0.jar;D:\Maven_Repository\cn\hutool\hutool-all\5.7.5\hutool-all-5.7.5.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-starter-web\2.5.2\spring-boot-starter-web-2.5.2.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-starter\2.5.2\spring-boot-starter-2.5.2.jar;D:\Maven_Repository\org\springframework\boot\spring-boot\2.5.2\spring-boot-2.5.2.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-starter-logging\2.5.2\spring-boot-starter-logging-2.5.2.jar;D:\Maven_Repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;D:\Maven_Repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;D:\Maven_Repository\org\apache\logging\log4j\log4j-to-slf4j\2.14.1\log4j-to-slf4j-2.14.1.jar;D:\Maven_Repository\org\apache\logging\log4j\log4j-api\2.14.1\log4j-api-2.14.1.jar;D:\Maven_Repository\org\slf4j\jul-to-slf4j\1.7.31\jul-to-slf4j-1.7.31.jar;D:\Maven_Repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;D:\Maven_Repository\org\yaml\snakeyaml\1.28\snakeyaml-1.28.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-starter-json\2.5.2\spring-boot-starter-json-2.5.2.jar;D:\Maven_Repository\com\fasterxml\jackson\core\jackson-databind\2.12.3\jackson-databind-2.12.3.jar;D:\Maven_Repository\com\fasterxml\jackson\core\jackson-annotations\2.12.3\jackson-annotations-2.12.3.jar;D:\Maven_Repository\com\fasterxml\jackson\core\jackson-core\2.12.3\jackson-core-2.12.3.jar;D:\Maven_Repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.12.3\jackson-datatype-jdk8-2.12.3.jar;D:\Maven_Repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.12.3\jackson-datatype-jsr310-2.12.3.jar;D:\Maven_Repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.12.3\jackson-module-parameter-names-2.12.3.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-starter-tomcat\2.5.2\spring-boot-starter-tomcat-2.5.2.jar;D:\Maven_Repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.48\tomcat-embed-core-9.0.48.jar;D:\Maven_Repository\org\apache\tomcat\embed\tomcat-embed-el\9.0.48\tomcat-embed-el-9.0.48.jar;D:\Maven_Repository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.48\tomcat-embed-websocket-9.0.48.jar;D:\Maven_Repository\org\springframework\spring-web\5.3.8\spring-web-5.3.8.jar;D:\Maven_Repository\org\springframework\spring-beans\5.3.8\spring-beans-5.3.8.jar;D:\Maven_Repository\org\springframework\spring-webmvc\5.3.8\spring-webmvc-5.3.8.jar;D:\Maven_Repository\org\springframework\spring-aop\5.3.8\spring-aop-5.3.8.jar;D:\Maven_Repository\org\springframework\spring-context\5.3.8\spring-context-5.3.8.jar;D:\Maven_Repository\org\springframework\spring-expression\5.3.8\spring-expression-5.3.8.jar;D:\Maven_Repository\com\github\nobugboy\ydoc-spring-boot-starter\1.1.2\ydoc-spring-boot-starter-1.1.2.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-autoconfigure\2.5.2\spring-boot-autoconfigure-2.5.2.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-starter-mail\2.5.2\spring-boot-starter-mail-2.5.2.jar;D:\Maven_Repository\org\springframework\spring-context-support\5.3.8\spring-context-support-5.3.8.jar;D:\Maven_Repository\com\sun\mail\jakarta.mail\1.6.7\jakarta.mail-1.6.7.jar;D:\Maven_Repository\com\sun\activation\jakarta.activation\1.2.2\jakarta.activation-1.2.2.jar;D:\Maven_Repository\com\alibaba\fastjson\1.2.76\fastjson-1.2.76.jar;D:\Maven_Repository\io\springfox\springfox-swagger2\2.9.2\springfox-swagger2-2.9.2.jar;D:\Maven_Repository\io\swagger\swagger-annotations\1.5.20\swagger-annotations-1.5.20.jar;D:\Maven_Repository\io\swagger\swagger-models\1.5.20\swagger-models-1.5.20.jar;D:\Maven_Repository\io\springfox\springfox-spi\2.9.2\springfox-spi-2.9.2.jar;D:\Maven_Repository\io\springfox\springfox-core\2.9.2\springfox-core-2.9.2.jar;D:\Maven_Repository\io\springfox\springfox-schema\2.9.2\springfox-schema-2.9.2.jar;D:\Maven_Repository\io\springfox\springfox-swagger-common\2.9.2\springfox-swagger-common-2.9.2.jar;D:\Maven_Repository\io\springfox\springfox-spring-web\2.9.2\springfox-spring-web-2.9.2.jar;D:\Maven_Repository\com\google\guava\guava\20.0\guava-20.0.jar;D:\Maven_Repository\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;D:\Maven_Repository\org\springframework\plugin\spring-plugin-core\1.2.0.RELEASE\spring-plugin-core-1.2.0.RELEASE.jar;D:\Maven_Repository\org\springframework\plugin\spring-plugin-metadata\1.2.0.RELEASE\spring-plugin-metadata-1.2.0.RELEASE.jar;D:\Maven_Repository\org\mapstruct\mapstruct\1.2.0.Final\mapstruct-1.2.0.Final.jar;D:\Maven_Repository\com\github\xiaoymin\swagger-bootstrap-ui\1.9.6\swagger-bootstrap-ui-1.9.6.jar;D:\Maven_Repository\org\springframework\boot\spring-boot-configuration-processor\2.5.2\spring-boot-configuration-processor-2.5.2.jar;D:\Maven_Repository\org\projectlombok\lombok\1.18.20\lombok-1.18.20.jar;D:\Maven_Repository\net\bytebuddy\byte-buddy\1.10.22\byte-buddy-1.10.22.jar;D:\Maven_Repository\org\springframework\spring-core\5.3.8\spring-core-5.3.8.jar;D:\Maven_Repository\org\springframework\spring-jcl\5.3.8\spring-jcl-5.3.8.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2019.2.4\lib\idea_rt.jar" com.bowu66.spider.SpiderManApplication
Connected to the target VM, address: '127.0.0.1:59760', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.2)

2021-12-08 20:55:05.048  INFO 74844 --- [           main] com.bowu66.spider.SpiderManApplication   : Starting SpiderManApplication using Java 9 on lenovo-legion with PID 74844 (D:\IdeaProjects\spider-man\target\classes started by legion in D:\IdeaProjects\spider-man)
2021-12-08 20:55:05.050  INFO 74844 --- [           main] com.bowu66.spider.SpiderManApplication   : No active profile set, falling back to default profiles: default
2021-12-08 20:55:05.762  INFO 74844 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-12-08 20:55:05.768  INFO 74844 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-12-08 20:55:05.769  INFO 74844 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.48]
2021-12-08 20:55:05.829  INFO 74844 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-12-08 20:55:05.829  INFO 74844 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 747 ms
2021-12-08 20:55:06.061  INFO 74844 --- [           main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
 _  _  ____  _____  ___ 
( \/ )(  _ \(  _  )/ __)
 \  /  )(_) ))(_)(( (__ 
 (__) (____/(_____)\___)
                v1.1.2   
2021-12-08 20:55:06.211  WARN 74844 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'controllerSwagger' defined in class path resource [com/github/ydoc/config/AutoConfig.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
2021-12-08 20:55:06.214  INFO 74844 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-12-08 20:55:06.220  INFO 74844 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-12-08 20:55:06.233 ERROR 74844 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'controllerSwagger' defined in class path resource [com/github/ydoc/config/AutoConfig.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.2.jar:2.5.2]
	at com.bowu66.spider.SpiderManApplication.main(SpiderManApplication.java:12) [classes/:na]
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.ArrayList.addAll(ArrayList.java:598) ~[na:na]
	at com.github.ydoc.core.RequestTypeMatchingSwagger.setHeaders(RequestTypeMatchingSwagger.java:26) ~[ydoc-spring-boot-starter-1.1.2.jar:1.1.2]
	at com.github.ydoc.core.ScanControllerSwagger.scan(ScanControllerSwagger.java:83) ~[ydoc-spring-boot-starter-1.1.2.jar:1.1.2]
	at com.github.ydoc.core.ScanControllerSwagger.afterPropertiesSet(ScanControllerSwagger.java:141) ~[ydoc-spring-boot-starter-1.1.2.jar:1.1.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.8.jar:5.3.8]
	... 16 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:59760', transport: 'socket'

Process finished with exit code 1

![image](https://user-images.githubusercontent.com/18244668/145212124-aa122d1f-2549-4bad-b12c-2f7aad67b1fc.png)

**Comment by NoBugBoy** [comment]
加上 ydoc.headers= 
后面可以什么都不填就行

这个确实是个问题下一版会修复
